import React from "react";
import "../styles/globals.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>ramonparis.dev</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name={"description"} content={"Ramón París portfolio page :)"} />
        <meta name="robots" content="index, follow" />
      </head>
      <body>{children}</body>
    </html>
  );
}
